services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis-network
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  userdb:
    image: "postgres:16-alpine"
    expose:
      - "${PG_PORT}"
    environment:
      POSTGRES_DB: ${USER_DB}
      POSTGRES_USER: ${USER_USER}
      POSTGRES_PASSWORD: ${USER_PASSWORD}
    volumes:
      - ./userdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${USER_USER} -d ${USER_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped
    networks:
      - user-network
  inventorydb:
    image: "postgres:16-alpine"
    expose:
      - "${PG_PORT}"
    environment:
      POSTGRES_DB: ${INV_DB}
      POSTGRES_USER: ${INV_USER}
      POSTGRES_PASSWORD: ${INV_PASSWORD}
    volumes:
      - ./inventorydb:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${INV_USER} -d ${INV_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped
    networks:
      - inventory-network
  conventiondb:
    image: "postgres:16-alpine"
    expose:
      - "${PG_PORT}"
    environment:
      POSTGRES_DB: ${CONV_DB}
      POSTGRES_USER: ${CONV_USER}
      POSTGRES_PASSWORD: ${CONV_PASSWORD}
    volumes:
      - ./conventiondb:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${CONV_USER} -d ${CONV_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped
    networks:
      - convention-network
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    expose:
      - "8000"
    depends_on:
      redis:
        condition: service_healthy
      userdb:
        condition: service_healthy
      inventory-service:
        condition: service_healthy
    environment:
      POSTGRES_DB: ${USER_DB}
      POSTGRES_USER: ${USER_USER}
      POSTGRES_PASSWORD: ${USER_PASSWORD}
      INVENTORY_BASE: http://inventory-service:8000
      REGISTRATION_BASE: http://registration-service:8000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_SERVICE: userdb
      POSTGRES_PORT: ${PG_PORT}
      # half a day in seconds for TTL user session
      TTL_SECONDS: 43200000
    restart: unless-stopped
    networks:
      - main-network
      - user-network
      - redis-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      replicas:  ${NUM_DUPES}
  inventory-service:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    expose:
      - "8000"
    depends_on:
      inventorydb:
        condition: service_healthy
    environment:
      POSTGRES_DB: ${INV_DB}
      POSTGRES_USER: ${INV_USER}
      POSTGRES_PASSWORD: ${INV_PASSWORD}
      POSTGRES_SERVICE: inventorydb
      POSTGRES_PORT: ${PG_PORT}
    networks:
      - main-network
      - inventory-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      replicas: ${NUM_DUPES}
  convention-service:
    build:
      context: ./convention-service
      dockerfile: Dockerfile
    expose:
      - "8000"
    depends_on:
      conventiondb:
        condition: service_healthy
    environment:
      POSTGRES_DB: ${CONV_DB}
      POSTGRES_USER: ${CONV_USER}
      POSTGRES_PASSWORD: ${CONV_PASSWORD}
      POSTGRES_SERVICE: conventiondb
      POSTGRES_PORT: ${PG_PORT}
    networks:
      - main-network
      - convention-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      replicas:  ${NUM_DUPES}
  booth-service:
    build:
      context: ./booth-service
      dockerfile: Dockerfile
    expose:
      - "8000"
    depends_on:
      conventiondb:
        condition: service_healthy
      convention-service:
        condition: service_healthy
    environment:
      POSTGRES_DB: ${CONV_DB}
      POSTGRES_USER: ${CONV_USER}
      POSTGRES_PASSWORD: ${CONV_PASSWORD}
      POSTGRES_SERVICE: conventiondb
      POSTGRES_PORT: ${PG_PORT}
    networks:
      - main-network
      - convention-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      replicas:  ${NUM_DUPES}
  registration-service:
    build:
      context: ./registration-service
      dockerfile: Dockerfile
    expose:
      - "8000"
    depends_on:
      conventiondb:
        condition: service_healthy
      convention-service:
        condition: service_healthy
    environment:
      POSTGRES_DB: ${CONV_DB}
      POSTGRES_USER: ${CONV_USER}
      POSTGRES_PASSWORD: ${CONV_PASSWORD}
      POSTGRES_SERVICE: conventiondb
      POSTGRES_PORT: ${PG_PORT}
    networks:
      - main-network
      - convention-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      replicas:  ${NUM_DUPES}
  nginx:
    image: nginx:alpine
    container_name: api-gateway
    depends_on:
      user-service:
        condition: service_healthy
      inventory-service:
        condition: service_healthy
      convention-service:
        condition: service_healthy
      booth-service:
        condition: service_healthy
      registration-service:
        condition: service_healthy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - main-network

volumes:
  redis-data:
networks:
  main-network:
    name: main-network
    driver: bridge
  redis-network:
    name: redis-network
    driver: bridge
  user-network:
    name: user-network
    driver: bridge
  inventory-network:
    name: inventory-network
    driver: bridge
  convention-network:
    name: convention-network
    driver: bridge
