services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis-network
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  userdb:
    image: "postgres:16-alpine"
    ports:
      # consider this later, manually mapping port to this db causes issues with ports for other dbs later
      - "${USER_PORT}:5432"
    environment:
      POSTGRES_DB: ${USER_DB}
      POSTGRES_USER: ${USER_USER}
      POSTGRES_PASSWORD: ${USER_PASSWORD}
    volumes:
      - ./userdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${USER_USER} -d ${USER_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped
    networks:
      - user-network
  inventorydb:
    image: "postgres:16-alpine"
    ports:
      # consider this later, manually mapping port to this db causes issues with ports for other dbs later
      - "${INV_PORT}:5432"
    environment:
      POSTGRES_DB: ${INV_DB}
      POSTGRES_USER: ${INV_USER}
      POSTGRES_PASSWORD: ${INV_PASSWORD}
    volumes:
      - ./inventorydb:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${INV_USER} -d ${INV_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped
    networks:
      - inventory-network
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    expose:
      - "8000"
    depends_on:
      # convention-service:
      #   condition: service_healthy
      redis:
        condition: service_healthy
      userdb:
        condition: service_healthy
      inventory-service:
        condition: service_healthy
    environment:
      POSTGRES_DB: ${USER_DB}
      POSTGRES_USER: ${USER_USER}
      POSTGRES_PASSWORD: ${USER_PASSWORD}
      INVENTORY_BASE: http://inventory-service:8000
      #CONVENTION_BASE: http://convention-service:8000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # come back and figure the naming conventions out later
      POSTGRES_SERVICE: conventiondeck-userdb-1
      POSTGRES_PORT: ${USER_PORT}
      # half a day in seconds for TTL user session
      TTL_SECONDS: 43200000
    restart: unless-stopped
    networks:
      - main-network
      - user-network
      - redis-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  inventory-service:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    expose:
      - "8000"
    depends_on:
      inventorydb:
        condition: service_healthy
    environment:
      POSTGRES_DB: ${INV_DB}
      POSTGRES_USER: ${INV_USER}
      POSTGRES_PASSWORD: ${INV_PASSWORD}
      POSTGRES_SERVICE: conventiondeck-inventorydb-1
      POSTGRES_PORT: ${INV_PORT}
    networks:
      - main-network
      - inventory-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  # convention-service:
  #   build:
  #     context: ./convention-service
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000"
  #   depends_on:
  #     redis:
  #       condition: service_healthy
  #     booth-service:
  #       condition: service_healthy
  #     registration-service:
  #       condition: service_healthy
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - BOOTH_BASE=http://booth-service:8000
  #     - REGISTRATION_BASE=http://booth-service:8000
  #   networks:
  #     - main-network
  #     - redis-network
  #   restart: unless-stopped
  #   healthcheck:
  #     test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 10s
  # booth-service:
  #   build:
  #     context: ./booth-service
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000"
  #   depends_on:
  #     redis:
  #       condition: service_healthy
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #   networks:
  #     - main-network
  #     - redis-network
  #   restart: unless-stopped
  #   healthcheck:
  #     test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 10s
  # registration-service:
  #   build:
  #     context: ./registration-service
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000"
  #   depends_on:
  #     redis:
  #       condition: service_healthy
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #   networks:
  #     - main-network
  #     - redis-network
  #   restart: unless-stopped
  #   healthcheck:
  #     test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 10s
  nginx:
    image: nginx:alpine
    container_name: api-gateway
    depends_on:
      user-service:
        condition: service_healthy
      inventory-service:
        condition: service_healthy
      # convention-service:
      #   condition: service_healthy
      # booth-service:
      #   condition: service_healthy
      # registration-service:
      #   condition: service_healthy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - main-network

volumes:
  redis-data:
networks:
  main-network:
    driver: bridge
  redis-network:
    driver: bridge
  user-network:
    driver: bridge
  inventory-network:
    driver: bridge
